/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#43474f",
        "on-primary-fixed": "#001b3f",
        "tertiary-fixed": "#ffdcc2",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#6b3b09",
        primary: "#002653",
        "surface-container-high": "#e8e7ec",
        "inverse-surface": "#2f3034",
        "surface-container-highest": "#e3e2e7",
        background: "#faf9fe",
        "on-background": "#1a1b1f",
        "secondary-container": "#feae2c",
        "on-secondary-fixed": "#291800",
        "surface-dim": "#dad9de",
        "primary-fixed": "#d7e3ff",
        "on-surface": "#1a1b1f",
        secondary: "#835500",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-container": "#5e3100",
        "on-tertiary": "#ffffff",
        "surface-bright": "#faf9fe",
        "surface-container-low": "#f4f3f8",
        "surface-tint": "#405e92",
        "on-primary-container": "#8aa8e0",
        outline: "#747780",
        "on-secondary-container": "#6b4500",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#db9960",
        "on-tertiary-fixed": "#2e1500",
        error: "#ba1a1a",
        "inverse-on-surface": "#f1f0f5",
        "on-secondary-fixed-variant": "#633f00",
        "outline-variant": "#c4c6d0",
        "on-primary-fixed-variant": "#264679",
        surface: "#faf9fe",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#abc7ff",
        "surface-variant": "#e3e2e7",
        "primary-container": "#1a3c6e",
        "secondary-fixed": "#ffddb4",
        "surface-container": "#eeedf2",
        "inverse-primary": "#abc7ff",
        tertiary: "#3e1f00",
        "secondary-fixed-dim": "#ffb955",
        "tertiary-fixed-dim": "#feb87c",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
}
